### ISSUE TITLE
Getting null reference exception

### ISSUE THREAD

**Issue by artisticcheese** [crossplane-contrib/provider-nop#23]
### What happened?
Resource fails and logs showing null reference exception

### How can we reproduce it?
Log
```
2025-05-23T15:47:34Z	DEBUG	provider-nop	External resource is up to date	{"controller": "managed/nopresource.nop.crossplane.io", "request": {"name":"my-demo-api-claim-ctfvv-z8t56"}, "uid": "6dd1b8cf-22c5-4ccb-865c-8d628efa0ba3", "version": "382069", "external-name": "my-demo-api-claim-ctfvv-z8t56", "requeue-after": "2025-05-23T15:47:44Z"}
E0523 15:47:34.206478       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 92 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x189e3a0, 0x2ad0dc0})
	k8s.io/apimachinery@v0.30.0/pkg/util/runtime/runtime.go:75 +0x85
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:103 +0xb2
panic({0x189e3a0?, 0x2ad0dc0?})
	runtime/panic.go:770 +0x132
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.ExternalClientFns.Disconnect(...)
	github.com/crossplane/crossplane-runtime@v1.17.0/pkg/reconciler/managed/reconciler.go:387
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile.func2()
	github.com/crossplane/crossplane-runtime@v1.17.0/pkg/reconciler/managed/reconciler.go:967 +0x258
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc00031c7e0, {0x1d9e208, 0xc0001d36e0}, {{{0x0, 0x0}, {0xc000480fe0, 0x1d}}})
	github.com/crossplane/crossplane-runtime@v1.17.0/pkg/reconciler/managed/reconciler.go:1253 +0x8e0b
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc0001a11d0, {0x1d9e208, 0xc0001d36e0}, {{{0x0?, 0x5?}, {0xc000480fe0?, 0xc00046bd10?}}})
	github.com/crossplane/crossplane-runtime@v1.17.0/pkg/ratelimiter/reconciler.go:54 +0x151
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1da2990?, {0x1d9e208?, 0xc0001d36e0?}, {{{0x0?, 0xb?}, {0xc000480fe0?, 0x0?}}})
	sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:114 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000fa840, {0x1d9e240, 0xc0001a0960}, {0x1928d80, 0xc0005f11a0})
	sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:311 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000fa840, {0x1d9e240, 0xc0001a0960})
	sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:261 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:222 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 46
	sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:218 +0x486
```
Resource 
```
          - name: no-op
            base:
              apiVersion: nop.crossplane.io/v1alpha1
              kind: NopResource
              spec:
                forProvider:
                  fields:
                    integerField: 42
                    stringField: "cool"
                    objectField:
                      stringField: "cool"
                    arrayField:
                      - stringField: "cool"
```
### What environment did it happen in?
Crossplane version: 1.20
